[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "siupylib"
version = "0.1"
dependencies = [
    "requests",
    "sqlalchemy",
    "pandas",
    "importlib-metadata"]
